# Generated by Django 6.0.5 on 2026-06-17 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song', models.CharField()),
                ('artist', models.CharField()),
                ('album', models.CharField()),
                ('year', models.IntegerField()),
            ],
        ),
    ]
